# Generated by Django 6.1.1 on 2026-09-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
