# Generated by Django 6.1.1 on 2026-10-03 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyhub', '0002_studyhubplan_updated_at_booking_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='duration_hours',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='session',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studyhubplan',
            name='duration_value',
        ),
        migrations.RemoveField(
            model_name='studyhubplan',
            name='is_active',
        ),
        migrations.AddField(
            model_name='studyhubsettings',
            name='max_lockers',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studyhub.booking'),
        ),
    ]
